@startuml tables
entity users {
    + id [PK]
    --
    name
    created_at
    updated_at
    deleted_at
}

entity user_settings {
    + id [PK]
    --
    user_id [FK]
    target_practice_seconds
    created_at
    updated_at
    deleted_at
}

entity user_instruments {
    + id [PK]
    --
    user_setting_id [FK]
    instrument_id [FK]
    is_main
    created_at
    updated_at
    deleted_at
}

entity instruments {
    + id [PK]
    --
    name
    created_at
    updated_at
    deleted_at
}

entity practice_categories {
    + id [PK]
    --
    name
    created_at
    updated_at
    deleted_at
}

entity practice_subcategories {
    + id [PK]
    --
    practice_category_id [FK]
    name
    created_at
    updated_at
    deleted_at
}

entity practice_menus {
    + id [PK]
    --
    practice_subcategory_id [FK]
    name
    is_user_defined
    created_at
    updated_at
    deleted_at
}

entity instrument_belonging_to_practice_menu {
    + id [PK]
    --
    instrument_id [FK]
    practice_menus_id [FK]
    is_user_defined
    created_at
    updated_at
    deleted_at
}

entity practice_records {
    + id [PK]
    --
    instrument_id [FK]
    practice_menu_id [FK]
    practice_seconds
    memo
    practiced_at
    created_at
    updated_at
    deleted_at
}



@enduml